feat: inicio de proyecto y configuracion
nsdonato/planetas_api pull request #1
Opened 2022-08-18 21:06 UTC by PabMai

Se agrego eslint, prettier, commitlint, kusky, typescript, express y prisma
Tambien se creo estructura de carpetas para el proyecto

2022-08-18 21:14 UTC, nsdonato requested changes

2022-08-18 21:14 UTC, nsdonato commented on .eslintrc.json
> +        "indent": [
Estas reglas las sacaría porque van a entrar en conflicto con prettier, sino proba tirando npx eslint-config-prettier src/*.* y te va a saltar

2022-08-18 22:42 UTC, PabMai commented on .eslintrc.json
> +        "indent": [
Listo, saque esas reglas. Ahora no se si tengo que actualizar algo en este PR

2022-08-18 23:06 UTC, nsdonato commented on .eslintrc.json
> +        "indent": [
te tiró conflicto la prueba? si las borraste deberías hacer un commit y pushear, porque acá no veo que lo hayas subido, puede ser?

2022-08-19 12:48 UTC, PabMai commented on .eslintrc.json
> +        "indent": [
Si me tiro conflictos, lo saque y despues hice push de esos cambios.

https://github.com/nsdonato/planetas_api/pull/1/commits/7f804ca4291673389507c48cb628bc26e834ad02

2022-08-19 12:55 UTC, nsdonato approved these changes

2022-08-19 12:58 UTC, ivanFlor3s approved these changes

2022-08-19 13:01 UTC, lovera00 approved these changes
Aprobado.

2022-08-19 13:37 UTC, merged