feat: diagrama de la base de datos
nsdonato/planetas_api pull request #4
Opened 2022-08-26 00:49 UTC by PabMai

Creación del diagrama de la base de datos

2022-08-26 00:51 UTC, lovera00 requested changes
Llevar al readme.md

2022-08-26 01:05 UTC, PabMai commented
Se agrego la imagen de la base de datos en el archivo README.md

2022-08-26 01:09 UTC, lovera00 approved these changes

2022-08-26 12:18 UTC, nsdonato requested changes
planeta_estadisca es un typo? o adrede?

2022-08-26 13:39 UTC, PabMai commented
Corrección en el nombre de tabla (error de tipeo)

2022-08-28 11:59 UTC, lovera00 approved these changes
Aprobado.

2022-08-28 13:53 UTC, nsdonato approved these changes

2022-08-28 15:14 UTC, merged